### ISSUE TITLE
Angular compatibility

### ISSUE THREAD

**Issue by ewomack2000** [geedmo/yamm#7]
Hello - is the new yamm 4 compatible with newer versions of Angular such as 8+? I tried some simple samples and they didn't seem to work, then I saw that there was once an "Angular MegaMenu" but for AngularJS. If it's not compatible, is there a newer version of the Angular MegaMenu? Thanks!

**Comment by geedmo** [comment]
Hello, this project is mainly css. There's no reason to be compatible with a JS framework like Angular. Meaning, it works with Bootstrap which is always the same. Please provide a reproducible case in order to check the issue. Thanks
